sudo: false
language: go
go_import_path: code.cloudfoundry.org/routing-release/gorouter/atomic

go:
  - 1.5
  - 1.6
  - tip

cache:
  directories:
    - vendor

install:
  - make install_ci

script:
  - make test_ci
  - scripts/test-ubergo.sh
  - make lint
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
